STUDENT PERFRORMANCE FACTORS
DATA ANALYSIS PROJECT
MADE USING PYTHON LIBRARIES

Importing Pandas and Numpy Libraries and reading the .csv file

In [203]:
import pandas as pd
import numpy as np

df = pd.read_csv('StudentPerformanceFactors.csv')

In [204]:
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

Checking and filtering out the null colums

In [205]:
df.isnull()
df.dropna()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

Checking wheater there are duplicate colums/rows or not

In [206]:
df.drop_duplicates().dropna()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

There are no duplicate colums/rows

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Highest Scorer in the Recent Exam

In [207]:
top_student_df = df[df['Exam_Score'] == df['Exam_Score'].max()]
top_student_df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
1525,27,98,Low,Medium,Yes,6,93,Low,No,5,High,High,Public,Positive,3,No,High School,Moderate,Female,101

List of top ten Higest scorers of the recent exam

In [208]:
df.sort_values(by='Exam_Score', ascending=False).head(10)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
1525,27,98,Low,Medium,Yes,6,93,Low,No,5,High,High,Public,Positive,3,No,High School,Moderate,Female,101
94,18,89,High,Medium,Yes,4,73,Medium,Yes,3,High,Medium,Private,Positive,2,No,College,Near,Female,100
2425,23,83,High,High,Yes,4,89,Low,Yes,1,Medium,Medium,Public,Negative,3,No,High School,Far,Male,99
3579,14,90,High,High,Yes,8,86,Medium,Yes,4,Medium,Medium,Private,Negative,2,No,High School,Near,Female,99
6347,28,96,High,Low,Yes,4,98,High,Yes,1,High,High,Public,Positive,3,No,High School,Near,Male,98
6393,16,83,Low,Medium,Yes,8,92,Low,Yes,2,High,High,Public,Positive,4,No,Postgraduate,Near,Female,98
4192,28,90,Low,Medium,Yes,9,91,Medium,Yes,0,Medium,Medium,Public,Positive,2,No,College,Moderate,Female,98
529,15,83,Medium,Medium,No,7,97,Medium,Yes,2,Low,High,Private,Neutral,2,No,High School,Near,Female,97
919,21,74,High,Medium,No,6,94,Medium,Yes,1,Low,High,Public,Positive,1,No,High School,Near,Male,97
5966,25,99,Medium,Medium,Yes,7,77,Medium,Yes,0,High,High,Public,Neutral,3,No,High School,Near,Male,97

Lowest Scorer In recent exam

In [209]:
low_student_df = df[df['Exam_Score'] == df['Exam_Score'].min()]
low_student_df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
1101,3,62,Medium,Low,No,6,67,Medium,Yes,1,Low,Medium,Public,Negative,3,No,High School,Near,Male,55

List of top ten lowest scorers in recent exam

In [210]:
df.sort_values(by='Exam_Score').head(10)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
1101,3,62,Medium,Low,No,6,67,Medium,Yes,1,Low,Medium,Public,Negative,3,No,High School,Near,Male,55
5507,5,65,Low,High,No,7,71,Medium,Yes,0,Low,Medium,Private,Negative,2,No,College,Far,Male,56
5907,3,60,Medium,Low,Yes,6,78,Low,Yes,1,Low,Medium,Public,Positive,1,No,Postgraduate,Near,Female,57
3543,14,67,Low,Low,Yes,7,66,Low,Yes,0,Low,Medium,Public,Neutral,4,No,High School,Far,Female,57
5719,9,64,Medium,Low,Yes,10,68,Low,Yes,0,Medium,Medium,Private,Negative,3,No,High School,Near,Male,57
2880,7,66,High,Low,Yes,8,68,High,Yes,0,Low,Medium,Public,Negative,2,Yes,College,Moderate,Male,57
6000,13,60,Low,Medium,No,5,67,High,Yes,1,Low,Medium,Public,Positive,4,Yes,High School,Far,Male,58
668,4,69,Medium,Low,No,9,93,Low,No,2,Medium,High,Private,Negative,3,No,High School,Moderate,Female,58
1750,4,61,Low,High,Yes,7,71,High,Yes,0,Low,Low,Public,Positive,1,No,Postgraduate,Near,Male,58
5198,15,60,High,Medium,No,7,63,Low,Yes,0,Low,High,Public,Positive,1,Yes,High School,Far,Female,58

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Adding a improvement status to show the progress of the student

In [211]:

df['Diffrence In Exam_Scores'] = df['Exam_Score'] - df['Previous_Scores']
df.loc[df['Diffrence In Exam_Scores'] == 0, 'Improvment_Status'] = "No Improvement"
df.loc[df['Diffrence In Exam_Scores'] > 0, 'Improvment_Status'] = "Improvement"
df.loc[df['Diffrence In Exam_Scores'] < 0, 'Improvment_Status'] = "Improvement Decline"

df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Diffrence In Exam_Scores,Improvment_Status
0,23,84,Low,High,No,7,73,Low,Yes,0,...,Public,Positive,3,No,High School,Near,Male,67,-6,Improvement Decline
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,Public,Negative,4,No,College,Moderate,Female,61,2,Improvement
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,Public,Neutral,4,No,Postgraduate,Near,Male,74,-17,Improvement Decline
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,Public,Negative,4,No,High School,Moderate,Male,71,-27,Improvement Decline
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,...,Public,Neutral,4,No,College,Near,Female,70,5,Improvement
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,...,Public,Positive,2,No,High School,Near,Female,68,-8,Improvement Decline
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,...,Public,Positive,2,No,High School,Near,Female,69,-12,Improvement Decline
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,...,Public,Negative,2,No,Postgraduate,Near,Female,68,3,Improvement
6605,10,86,High,High,Yes,6,91,High,Yes,2,...,Private,Positive,3,No,High School,Far,Female,68,-23,Improvement Decline
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,...,Public,Positive,4,No,Postgraduate,Near,Male,64,-30,Improvement Decline

Showing how many students have improved from the previous exam

In [212]:
df['Improvment_Status'].value_counts()

Improvment_Status
Improvement Decline    4332
Improvement            2140
No Improvement          135
Name: count, dtype: int64

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

the student who made the highest improvment

In [213]:
df[df['Diffrence In Exam_Scores'] == df['Diffrence In Exam_Scores'].max()]

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Diffrence In Exam_Scores,Improvment_Status
6522,18,90,High,High,Yes,6,54,Low,Yes,1,...,Public,Negative,3,No,High School,Near,Female,95,41,Improvement

the students who made the lowest improvment

In [214]:
df[df['Diffrence In Exam_Scores'] == df['Diffrence In Exam_Scores'].min()]

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Diffrence In Exam_Scores,Improvment_Status
1160,5,65,Medium,High,Yes,7,98,Low,Yes,1,...,Private,Positive,3,No,High School,Far,Male,59,-39,Improvement Decline
5896,11,63,Medium,Medium,Yes,10,100,High,Yes,0,...,Public,Neutral,3,No,High School,Far,Female,61,-39,Improvement Decline
6448,6,67,Medium,Low,Yes,6,99,Low,Yes,0,...,Private,Neutral,2,No,College,Near,Male,60,-39,Improvement Decline

Average marks of all students

In [215]:
int(df['Exam_Score'].mean())

67

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Relationship analysis

In [216]:
df.groupby('Physical_Activity')['Improvment_Status'].value_counts()  #Plan To make it in Graph

Physical_Activity  Improvment_Status
0                  Improvement Decline      35
                   Improvement              11
1                  Improvement Decline     267
                   Improvement             147
                   No Improvement            7
2                  Improvement Decline    1068
                   Improvement             528
                   No Improvement           31
3                  Improvement Decline    1686
                   Improvement             807
                   No Improvement           52
4                  Improvement Decline    1031
                   Improvement             507
                   No Improvement           37
5                  Improvement Decline     225
                   Improvement             131
                   No Improvement            5
6                  Improvement Decline      20
                   Improvement               9
                   No Improvement            3
Name: count, dtype: int64

In [217]:
df.groupby('Internet_Access')['Improvment_Status'].value_counts()  #Plan To make it in Graph

Internet_Access  Improvment_Status
No               Improvement Decline     332
                 Improvement             153
                 No Improvement           14
Yes              Improvement Decline    4000
                 Improvement            1987
                 No Improvement          121
Name: count, dtype: int64

In [218]:
df.groupby('Sleep_Hours')['Internet_Access'].value_counts() #Plan To make it in Graph

Sleep_Hours  Internet_Access
4            Yes                 293
             No                   16
5            Yes                 638
             No                   57
6            Yes                1265
             No                  111
7            Yes                1599
             No                  142
8            Yes                1293
             No                  106
9            Yes                 725
             No                   50
10           Yes                 295
             No                   17
Name: count, dtype: int64

In [219]:
df.groupby('Learning_Disabilities')['Motivation_Level'].value_counts()

Learning_Disabilities  Motivation_Level
No                     Medium              3018
                       Low                 1723
                       High                1171
Yes                    Medium               333
                       Low                  214
                       High                 148
Name: count, dtype: int64

In [220]:
df.groupby('Family_Income')['Access_to_Resources'].value_counts()

Family_Income  Access_to_Resources
High           Medium                  650
               High                    381
               Low                     238
Low            Medium                 1308
               High                    831
               Low                     533
Medium         Medium                 1361
               High                    763
               Low                     542
Name: count, dtype: int64

In [221]:
df.groupby('Teacher_Quality')['School_Type'].value_counts()

Teacher_Quality  School_Type
High             Public         1347
                 Private         600
Low              Public          463
                 Private         194
Medium           Public         2733
                 Private        1192
Name: count, dtype: int64

In [222]:
df.groupby('Teacher_Quality')['Exam_Score'].mean()

Teacher_Quality
High      67.676939
Low       66.753425
Medium    67.109299
Name: Exam_Score, dtype: float64

In [223]:
df.groupby('Peer_Influence')['Exam_Score'].mean() #Plan To make it in Graph

Peer_Influence
Negative    66.564270
Neutral     67.197917
Positive    67.623199
Name: Exam_Score, dtype: float64